### ISSUE TITLE
Test interfaces

### ISSUE THREAD

**Issue by Fixolito** [Fixolito/DualNumbers#5]
To do:
- [x] ``IAdditionOperators<Dual,Dual,Dual>``
- [x] ``IAdditiveIdentity<Dual,Dual>``
- [x] ``IDecrementOperators<Dual>``
- [x] ``IDivisionOperators<Dual,Dual,Dual>``
- [x] ``IEqualityOperators<Dual,Dual,bool>``
- [x] ``IEquatable<Dual>``
- [x] ``IFormatable``
- [x] ``IIncrementOperators<Dual>``
- [x] ``IMultiplicativeIdentity<Dual,Dual>``
- [x] ``IMultiplyOperators<Dual,Dual,Dual>``
- [x] ``INumber<Dual>`` huge
- [x] ``INumberBase<Dual>`` huge
- [x] ``IParsable<Dual>``
- [x] ``ISignedNumber<Dual>``
- [x] ``ISpanFormatable``
- [x] ``ISpanParsable<Dual>``
- [x] ``ISubtractionOperators<Dual,Dual,Dual>``
- [x] ``IUnaryNegationOperators<Dual,Dual>``
- [x] ``IUnaryPlusOperators<Dual,Dual>``
- [x] ``IUtf8SpanParsable<Dual>``

**Comment by n1k1010** [comment]
All InterfaceTests are complete and working

**Comment by n1k1010** [comment]
close after review
